"""Central Codex CLI subprocess management.

Solves three cross-cutting concerns:

1. PATH resolution — finds the `codex` binary even when the daemon runs
   under launchd's minimal PATH. Uses shutil.which + fallback directories.
2. Subprocess env — prepends standard binary directories so `codex exec`
   still resolves under launchd/systemd's minimal environment.
3. Error classification — distinguishes INFRA (missing binary, perm
   denied, auth failure) from TRANSIENT (timeout, Codex's own is_error)
   from PARSE (bad JSON). Retry accounting only penalizes non-INFRA.

Also maintains a registry of in-flight subprocesses so daemon shutdown
can terminate them instead of orphaning them.

Why we pass an absolute path: Python's subprocess lookup for the
executable when `env=` is supplied is implementation-dependent across
POSIX platforms — some paths use the parent's PATH, some use env[PATH].
Passing an already-resolved absolute path sidesteps the ambiguity and
guarantees the daemon finds `codex` regardless of who spawned it
(launchd, systemd, hook, or interactive shell).
"""

import asyncio
import json
import os
import shutil
import tempfile
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Iterable, Optional

OBSERVER_SENTINEL = "[Codex Chronicle observer session]"
OBSERVER_PROMPT_PREFIX = (
    f"{OBSERVER_SENTINEL}\n"
    "This prompt is generated by Codex Chronicle while summarizing or synthesizing "
    "existing Codex sessions. Do not treat this observer run as user project work.\n\n"
)


def _fallback_bin_dirs() -> list[Path]:
    """Dirs to search when shutil.which("codex") misses.

    Computed per-call so HOME changes (e.g. test fixtures) are honored.
    """
    return [
        Path.home() / ".local" / "bin",
        Path("/opt/homebrew/bin"),
        Path("/usr/local/bin"),
    ]


def _standard_path_dirs() -> list[Path]:
    """Dirs prepended to the subprocess PATH so nested invocations work
    under launchd's minimal env."""
    return [
        Path.home() / ".local" / "bin",
        Path("/opt/homebrew/bin"),
        Path("/usr/local/bin"),
        Path("/usr/bin"),
        Path("/bin"),
        Path("/usr/sbin"),
        Path("/sbin"),
    ]


class ErrorKind(Enum):
    """Classification of subprocess failures."""
    INFRA = "infra"          # Binary missing, perm denied, auth — don't charge retries
    TRANSIENT = "transient"  # Timeout, Codex's is_error — count against retries
    PARSE = "parse"          # Output unparseable — count against retries


class CodexNotFound(RuntimeError):
    """Raised when the Codex binary cannot be resolved."""


@dataclass
class CodexResult:
    """Outcome of a `codex exec` invocation.

    If error_kind is None the call succeeded and stdout_json holds the
    parsed outer JSON. Otherwise error_message describes the failure.
    """
    stdout_json: Optional[dict] = None
    total_cost_usd: float = 0.0
    error_kind: Optional[ErrorKind] = None
    error_message: str = ""

    @property
    def ok(self) -> bool:
        return self.error_kind is None


# ---------- Binary resolution ----------

_cached_codex_path: Optional[Path] = None


def resolve_codex_binary(force_refresh: bool = False) -> Path:
    """Return the absolute path to `codex`. Raises CodexNotFound if absent.

    Searches os.environ["PATH"] (via shutil.which), then curated fallback
    dirs. Caches the hit for the process lifetime.
    """
    global _cached_codex_path
    if _cached_codex_path is not None and not force_refresh:
        if _cached_codex_path.exists():
            return _cached_codex_path
        _cached_codex_path = None

    hit = shutil.which("codex")
    if hit:
        _cached_codex_path = Path(hit).resolve()
        return _cached_codex_path

    for d in _fallback_bin_dirs():
        candidate = d / "codex"
        if candidate.exists() and os.access(candidate, os.X_OK):
            _cached_codex_path = candidate.resolve()
            return _cached_codex_path

    searched = [os.environ.get("PATH", "")] + [str(d) for d in _fallback_bin_dirs()]
    raise CodexNotFound(
        "Could not find `codex` binary. Searched: "
        + " | ".join(searched)
        + ". Install Codex CLI or ensure it is on the daemon's PATH "
        "(see `codex-chronicle doctor`)."
    )


def try_resolve_codex_binary() -> Optional[Path]:
    """Like resolve_codex_binary but returns None on miss instead of raising."""
    try:
        return resolve_codex_binary()
    except CodexNotFound:
        return None


def build_subprocess_env(base: Optional[dict] = None) -> dict:
    """Env dict suitable for spawning `codex exec`.

    - Strips ANTHROPIC_* credentials so they don't leak into the OpenAI
      Codex subprocess (and don't confuse third-party tooling on PATH).
      The Codex CLI reads its own auth from ~/.codex/auth.json or OPENAI_*
      env vars — ANTHROPIC_* are never useful here.
    - Prepends standard bin dirs to PATH so subprocess nested under Codex
      also works under launchd/systemd minimal env.
    - Marks the spawn so nested tooling (hooks, etc.) can recognize a
      Codex Chronicle observer call and bail out.
    """
    src = base if base is not None else os.environ
    env = {k: v for k, v in src.items() if not k.startswith("ANTHROPIC_")}
    existing = env.get("PATH", "").split(os.pathsep) if env.get("PATH") else []
    extra = [str(d) for d in _standard_path_dirs() if d.exists()]
    seen: set[str] = set()
    merged: list[str] = []
    for p in extra + existing:
        if p and p not in seen:
            seen.add(p)
            merged.append(p)
    env["PATH"] = os.pathsep.join(merged)
    env["CODEX_CHRONICLE_OBSERVER"] = "1"
    return env


# ---------- Subprocess registry (graceful shutdown) ----------

_active_procs: "set[asyncio.subprocess.Process]" = set()


def _register(proc: "asyncio.subprocess.Process") -> None:
    _active_procs.add(proc)


def _unregister(proc: "asyncio.subprocess.Process") -> None:
    _active_procs.discard(proc)


async def terminate_active_subprocesses(grace_seconds: float = 5.0) -> dict:
    """Terminate all in-flight Codex subprocesses. Called on daemon shutdown.

    Sends SIGTERM, waits up to grace_seconds, then SIGKILL stragglers.
    Always reaps via wait() after kill to avoid zombies.
    Returns {"terminated": N, "killed": M} for logging.
    """
    if not _active_procs:
        return {"terminated": 0, "killed": 0}
    victims = list(_active_procs)
    for p in victims:
        try:
            p.terminate()
        except ProcessLookupError:
            pass
    await asyncio.sleep(grace_seconds)
    killed = 0
    for p in victims:
        if p.returncode is None:
            try:
                p.kill()
                killed += 1
            except ProcessLookupError:
                pass
    # Reap all victims so we don't leave zombies.
    for p in victims:
        try:
            await asyncio.wait_for(p.wait(), timeout=2.0)
        except (asyncio.TimeoutError, ProcessLookupError):
            pass
    return {"terminated": len(victims), "killed": killed}


def active_subprocess_count() -> int:
    """For diagnostics / tests."""
    return len(_active_procs)


# ---------- Core invocation ----------

async def spawn_codex(
    prompt: str,
    *,
    model: str,
    fallback_model: str = "",
    effort: str = "high",
    json_schema: Optional[dict] = None,
    extra_flags: Iterable[str] = (),
    timeout: float = 300.0,
) -> CodexResult:
    """Invoke `codex exec` and return a classified result.

    Never raises for expected failure paths; returns a CodexResult with
    error_kind set. The caller decides whether that counts against a
    retry budget (see ErrorKind).
    """
    # Kept for compatibility with older callers; Codex CLI has no fallback
    # model flag, and current call sites should route via config.model.
    _ = fallback_model

    try:
        codex_bin = resolve_codex_binary()
    except CodexNotFound as e:
        return CodexResult(error_kind=ErrorKind.INFRA, error_message=str(e))

    schema_path: str | None = None
    output_path: str | None = None
    try:
        if json_schema is not None:
            schema_file = tempfile.NamedTemporaryFile(
                mode="w", suffix=".schema.json", delete=False
            )
            with schema_file:
                json.dump(json_schema, schema_file)
            schema_path = schema_file.name

        output_file = tempfile.NamedTemporaryFile(
            mode="w", suffix=".json", delete=False
        )
        output_path = output_file.name
        output_file.close()

        args = [
            str(codex_bin), "exec",
            "--json",
            "--ephemeral",
            "--skip-git-repo-check",
            "--sandbox", "read-only",
            "-c", 'approval_policy="never"',
            "-c", f'model_reasoning_effort="{effort}"',
            "-o", output_path,
        ]
        if model:
            args += ["--model", model]
        if schema_path:
            args += ["--output-schema", schema_path]
        args += list(extra_flags)
        args += ["-"]

        env = build_subprocess_env()

        try:
            proc = await asyncio.create_subprocess_exec(
                *args,
                stdin=asyncio.subprocess.PIPE,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                env=env,
            )
        except FileNotFoundError as e:
            return CodexResult(
                error_kind=ErrorKind.INFRA,
                error_message=f"codex binary vanished before spawn: {e}",
            )
        except PermissionError as e:
            return CodexResult(
                error_kind=ErrorKind.INFRA,
                error_message=f"permission denied spawning codex: {e}",
            )

        _register(proc)
        try:
            try:
                observer_prompt = OBSERVER_PROMPT_PREFIX + prompt
                stdout_bytes, stderr_bytes = await asyncio.wait_for(
                    proc.communicate(observer_prompt.encode()), timeout=timeout
                )
            except asyncio.TimeoutError:
                try:
                    proc.kill()
                    await proc.communicate()
                except Exception:
                    pass
                return CodexResult(
                    error_kind=ErrorKind.TRANSIENT,
                    error_message=f"codex exec timed out after {timeout}s",
                )
        finally:
            _unregister(proc)

        stdout = stdout_bytes.decode(errors="replace")
        stderr = stderr_bytes.decode(errors="replace")

        # is_error can appear inside a top-level JSON result even on exit 0 —
        # treat that as a transient-code path so the retry accounting charges
        # the attempt rather than silently swallowing the failure.
        top_level = _try_parse_single_json(stdout)
        if proc.returncode == 0 and isinstance(top_level, dict) and top_level.get("is_error"):
            msg = (top_level.get("result") or top_level.get("error") or "codex reported is_error")
            return CodexResult(
                error_kind=ErrorKind.TRANSIENT,
                error_message=str(msg)[:500],
                total_cost_usd=float(top_level.get("total_cost_usd") or 0.0),
            )

        if proc.returncode != 0:
            msg = stderr[:500] or stdout[:500] or f"exit {proc.returncode}"
            combined = (stderr + " " + stdout).lower()
            infra_hints = (
                "command not found", "no such file",
                "not authenticated", "authentication required",
                "unauthorized", "please run", "please log in",
                "api key", "auth.json", "login",
            )
            if any(h in combined for h in infra_hints):
                return CodexResult(error_kind=ErrorKind.INFRA, error_message=msg)
            return CodexResult(error_kind=ErrorKind.TRANSIENT, error_message=msg)

        total_cost = _extract_total_cost(stdout, top_level)

        final_text = ""
        if output_path:
            try:
                final_text = Path(output_path).read_text().strip()
            except OSError:
                final_text = ""
        if not final_text:
            final_text = _last_assistant_message_from_jsonl(stdout)
        # Fall back to the outer JSON if the Codex stub emitted a single
        # `{structured_output: ..., result: ..., total_cost_usd: ...}` object
        # on stdout instead of a JSONL stream — tests and older CLI versions
        # take this path.
        if not final_text and isinstance(top_level, dict):
            if "structured_output" in top_level:
                return CodexResult(
                    stdout_json={"structured_output": top_level["structured_output"]},
                    total_cost_usd=total_cost,
                )
            if top_level.get("result"):
                final_text = str(top_level["result"]).strip()

        if json_schema is None:
            return CodexResult(
                stdout_json={"result": final_text},
                total_cost_usd=total_cost,
            )

        try:
            structured = _parse_json_object(final_text)
        except (json.JSONDecodeError, ValueError) as e:
            return CodexResult(
                error_kind=ErrorKind.PARSE,
                error_message=f"structured output parse failed: {e}; stdout={stdout[:200]}",
                total_cost_usd=total_cost,
            )

        return CodexResult(
            stdout_json={"structured_output": structured},
            total_cost_usd=total_cost,
        )
    finally:
        for p in (schema_path, output_path):
            if p:
                try:
                    Path(p).unlink()
                except OSError:
                    pass


def _parse_json_object(text: str) -> dict:
    raw = (text or "").strip()
    if raw.startswith("```"):
        lines = raw.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].startswith("```"):
            lines = lines[:-1]
        raw = "\n".join(lines).strip()
    data = json.loads(raw)
    if not isinstance(data, dict):
        raise ValueError("final response was not a JSON object")
    return data


def _try_parse_single_json(text: str) -> Optional[dict]:
    """Parse stdout as a single JSON object if it is one. None otherwise.

    Older codex CLI versions (and the functional-test stub) emit one object
    rather than a JSONL stream — we fall back to it for error + cost fields.
    """
    raw = (text or "").strip()
    if not raw or not raw.startswith("{"):
        return None
    try:
        data = json.loads(raw)
    except (json.JSONDecodeError, ValueError):
        return None
    return data if isinstance(data, dict) else None


def _extract_total_cost(stdout: str, top_level: Optional[dict]) -> float:
    """Best-effort cost extraction from Codex output.

    Checks (in order):
      1. Top-level `total_cost_usd` on a single-object stdout.
      2. Any JSONL event with `total_cost_usd` (top-level or under `payload`)
         — Codex emits a summary event at the end of a run.
    Returns 0.0 if nothing is found; the caller displays cost only when > 0.
    """
    if isinstance(top_level, dict):
        raw = top_level.get("total_cost_usd")
        if isinstance(raw, (int, float)):
            return float(raw)

    total = 0.0
    for line in stdout.splitlines():
        line = line.strip()
        if not line or not line.startswith("{"):
            continue
        try:
            event = json.loads(line)
        except (json.JSONDecodeError, ValueError):
            continue
        if not isinstance(event, dict):
            continue
        for candidate in (event.get("total_cost_usd"),
                          (event.get("payload") or {}).get("total_cost_usd")
                          if isinstance(event.get("payload"), dict) else None):
            if isinstance(candidate, (int, float)):
                total = float(candidate)  # latest wins — cumulative from Codex
    return total


def _last_assistant_message_from_jsonl(stdout: str) -> str:
    last = ""
    for line in stdout.splitlines():
        try:
            event = json.loads(line)
        except json.JSONDecodeError:
            continue
        msg = event.get("message") or event.get("content") or ""
        if isinstance(msg, str) and msg.strip():
            last = msg.strip()
        payload = event.get("payload")
        if isinstance(payload, dict):
            text = payload.get("message") or payload.get("text")
            if isinstance(text, str) and text.strip():
                last = text.strip()
    return last


# ---------- Test hooks ----------

def _reset_cache_for_tests() -> None:
    """Called only from tests to clear cached state between runs."""
    global _cached_codex_path
    _cached_codex_path = None
    _active_procs.clear()
